"""Architecture: typed logits / typed targets / sampler / library / encoder."""

from .encoder import encode_library, encode_named_arch
from .library import (
    ANSWERER_ROLES,
    CANONICAL_FAMILIES,
    CRITIC,
    EXPERT,
    PLANNER,
    REFINER,
    RESEARCHER,
    ROLE_POOL,
    ROLE_TO_ID,
    SOLVER,
    TESTER,
    VERIFIER,
    NamedArch,
    canonical_library,
    default_inject_pool,
    family_of,
    full_library,
    full_mesh,
    imperfect_library,
    named_arch_to_concrete,
    random_archs,
    sample_inject_family_stratified,
)
from .sampler import (
    ConcreteArch,
    log_prob_edges,
    log_prob_gates,
    log_prob_joint,
    log_prob_pl,
    log_prob_roles,
    sample_arch,
    sample_pl,
)
from .spec import ArchLogits, ArchTargets, active_pair_mask

__all__ = [
    "ANSWERER_ROLES",
    "ArchLogits",
    "ArchTargets",
    "CANONICAL_FAMILIES",
    "CRITIC",
    "ConcreteArch",
    "EXPERT",
    "NamedArch",
    "PLANNER",
    "REFINER",
    "RESEARCHER",
    "ROLE_POOL",
    "ROLE_TO_ID",
    "SOLVER",
    "TESTER",
    "VERIFIER",
    "active_pair_mask",
    "canonical_library",
    "default_inject_pool",
    "encode_library",
    "encode_named_arch",
    "family_of",
    "full_library",
    "full_mesh",
    "imperfect_library",
    "log_prob_edges",
    "log_prob_gates",
    "log_prob_joint",
    "log_prob_pl",
    "log_prob_roles",
    "named_arch_to_concrete",
    "random_archs",
    "sample_arch",
    "sample_inject_family_stratified",
    "sample_pl",
]
